[package]
name = "moon"
version = "0.1.0"
authors = [ "Robey Pointer <robeypointer@gmail.com>" ]

[lib]
name = "moon"
crate-type = [ "staticlib" ]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
